name: Merge Pull Request
description: 'Auto Merge Pull Requests'
author: Sanjali Nagare
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  number:
    description: 'Pull Request number'
    required: true
  method:
    description: 'Green button merge type (merge, squash, rebase)'
    default: true
    required: true
  repo:
    description: 'Pull Request repo in owner/repo format'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
